# Site settings
title: Noah Hamann
email: njhamann@gmail.com
description: > 
    I am a front-end engineer located in Minneapolis, MN.
baseurl: ""
url: "http://noahhamann.com"
twitter_username: njhamann
github_username:  njhamann

# Build settings
markdown: kramdown
